server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: gateway-server

spring:
  cloud:
    gateway:
      # default-filters: LoggingGatewayFilterFactory
      discovery:
        locator:
          enabled: true
      routes:
        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/catalog/**
        # - id: movie-service
        #   uri: lb://movie-service
        #   predicates:
        #     - Path=/movie/**

