server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      default-filters: LoggingGatewayFilterFactory
      discovery:
        locator:
          enabled: true
      routes:
        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/catalog/**
            - Path=/message
          filters:
            - AddHeader=custom-user-header,custom-user-header-value
        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/movies/**
            - Path=/message
          filters:
              - AddHeader=custom-car-header,custom-car-header-value

