
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

message: hello from serie-service


server:
  port: 8083
spring:
  data:
    mongodb:
      database: ajeaPeli
      port: 27017
      host: localhost
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

queue:
  movie:
    name: serieQueue
zipkin:
  base-url: http://localhost:9411/

#actuator 
management:
  health:
    circuitbreakers:
      enabled: true
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
info:
  name: serie-service
  description: serie
  version: 1.0.0
  date: 2022-09-23