server:
  port: ${PORT:8888}
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/angelestrada14019/spring-cloud-design-patterns
          search-paths: config-data
          default-label: main
